# Generated by Django 4.1.2 on 2022-10-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('ID_flat', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('Area', models.IntegerField()),
            ],
            options={
                'db_table': 'Flat',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('Number_pasport', models.IntegerField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=255)),
                ('Second_name', models.CharField(max_length=255)),
                ('Phone_number', models.IntegerField()),
            ],
            options={
                'db_table': 'People',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('ID_access', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Condition', models.CharField(max_length=255)),
                ('Reason', models.CharField(max_length=255)),
                ('ID_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeapp.flat')),
                ('Number_pasport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeapp.people')),
            ],
            options={
                'db_table': 'Access',
            },
        ),
    ]
