# Generated by Django 4.1.2 on 2022-10-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='Date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='access',
            name='Reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='Area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='Type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='Phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
