# Generated by Django 4.1.2 on 2022-10-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0002_alter_access_date_alter_access_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Number_pasport',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
