# Generated by Django 4.1.2 on 2022-10-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0003_alter_people_number_pasport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
