# Generated by Django 4.1.2 on 2022-10-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0004_alter_people_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='Password',
            field=models.BigIntegerField(default=16845531),
        ),
    ]
