# Generated by Django 4.1.3 on 2022-12-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0007_rename_condition_access_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='password',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
