# Generated by Django 4.1.2 on 2022-12-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0008_people_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='humidity',
            field=models.DecimalField(decimal_places=1, default=50.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='flat',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=30.0, max_digits=5),
        ),
    ]
